name: Build and push docker image
on:
  push:
    branches:
      - docker-deploy
jobs:
  push-to-docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build and push docker image
        run: docker-push-bv
