name: Build and push docker image
on:
  pull_request:
    types: [closed]
    branches:
      - docker-deploy
jobs:
  push-to-docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build and push docker image
        run: |
          echo "--running push-to-docker-deploy--"
          echo "--PR merged?-- ${{ github.event.pull_request.merged }}"
          echo "--pwd-- $(pwd)"
          echo "--ls--"
          ls
          echo "------------------------------"
          echo "--ls ./bts--"
          ls ./bts
          echo "------------------------------"
          echo "--ls ./bts/.github--"
          ls ./bts/.github
          echo "------------------------------"
          echo "--ls ./bts/.github/workflows--"
          ls ./bts/.github/workflows
          echo "------------------------------"
          cd bts
          gh run --shell ./docker-push-bv
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_ID }}
