name: Auto merge from 'master' to 'docker-deploy'
on:
  push:
    branches:
      - master
jobs:
  merge-to-docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.WORKFLOW_ID }}
        name: Merge from 'master' to 'docker-deploy'
        run: |
          gh repo clone docker-deploy
          gh pr merge master -m --auto
